[package]
name = "test-project"
version = "0.1.0"
authors = ["Vesa Kaihlavirta <vegai@iki.fi>"]
license = "MIT"
build = "build.rs"

[lib]
name = "test_project"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.15"

[dependencies]
neon = "0.1.15"
