[package]
name = "serde-test"
version = "0.1.0"
authors = ["vegai"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = { version = "0.4", default_features = false, features = ["serde"] }
